name: 01.IO_Flush/1.1

on:
  push:
    branches:
      - main
      - 03-github-workflow
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: C requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc

      - name: Compile the program
        run: |
          cd 01.IO_Flush/1.1
          make

      - name: Run program
        run: |
          cd 01.IO_Flush/1.1
          make run

      - name: Add \n to output
        run: |
          cd 01.IO_Flush/1.1
          make run-n

      - name: Remove fflush and run
        run: |
            cd 01.IO_Flush/1.1
            make run-f

      - name: Redirect output to file
        run: |
            cd 01.IO_Flush/1.1 
            make run-r

      - name: Clean build
        run: |
            cd 01.IO_Flush/1.1 
            make clean