name: CI for Program with Options

on:
  push:
    branches:
      - main
      - 03-github-workflow
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: C requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc

      - name: Run the shell script
        run: |
          chmod +x script.sh
          ./script.sh

      - name: Check output.log
        run: cat output.log

